lib/masterminds_web/router.ex
defmodule MastermindsWeb.Router do
  use MastermindsWeb, :router
  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", MastermindsWeb do
    pipe_through :browser
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", MastermindsWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/logout", AuthController, :logout
    resources "/posts", PostController
    get "/quizzes/:topic", QuizController, :begin
  end

  # Other scopes may use custom stacks.
  # scope "/api", MastermindsWeb do
  #   pipe_through :api
  # end
end

lib/masterminds_web/views/layout_view.ex
defmodule MastermindsWeb.LayoutView do
  use MastermindsWeb, :view
  import Plug.Conn
  @spec logged_in?(Plug.Conn.t()) :: boolean()
  def logged_in?(conn) do
    !!get_session(conn, :user_id)
  end
end

lib/masterminds_web/templates/layout/_navbar.html.eex
<nav class="ui fixed inverted menu" role="navigation">
  <div class="ui container">

    <a href="/" class="header item">
      <img class="logo" src="<%= Routes.static_path(@conn, "/images/chip.svg") %>" alt="Masterminds Logo - CPU Chip"/>
       <span class="app-name"> Masterminds </span>
    </a>

    <div class="item">
      <a href="#">Link</a>
    </div>

    <div class="right menu">

     <%= if logged_in?(@conn) do %>

      <div class="item">
       <%= link raw(~s'<i class="list alternate icon"></i>Posts'), to: Routes.post_path(@conn, :index), class: "ui compact teal button" %>
      </div>

    <div class="item">
      <%= link raw(~s'<i class="sign out alternate icon"></i>Log out'), to: Routes.auth_path(@conn, :logout), class: "ui compact red button" %>
     </div>

      <div class="item">
        <div class="ui icon input">
          <%= form_for @conn, Routes.post_path(@conn, :index),
          [method: :get, class: "ui search"], fn f -> %>
          <%= search_input f, :query, class: "prompt", placeholder: "search for posts..." %>
          <%= submit "Search", class: "ui compact inverted primary button" %>
          <% end %>
        </div>
      </div>




      <% else %>

      <div class="item">
        <%= link raw(~s'<i class="sign in alternate icon"></i>Log in'), to: "/auth/auth0", class: "ui compact primary button" %>
      </div>

      <% end %>

    </div>
  </div>
</nav>

lib/masterminds_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Masterminds</title>
         <!-- Semantic-UI minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>

    <%= render "_navbar.html", conn: @conn %>

    <main role="main" class="ui container" id="app_wrapper">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Semantic-UI minified JS -->
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>